"""emotional_health_tables

Revision ID: 943753881737
Revises: fab70df98a04
Create Date: 2026-07-01 19:53:27.014238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '943753881737'
down_revision: Union[str, Sequence[str], None] = 'fab70df98a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crisis_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('resource_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('contact_info', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crisis_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crisis_resources_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_crisis_resources_country_code'), ['country_code'], unique=False)

    op.create_table('emotional_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disclaimer_accepted', sa.Boolean(), nullable=False),
    sa.Column('is_female', sa.Boolean(), nullable=False),
    sa.Column('crisis_alert', sa.Boolean(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotional_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emotional_assessments_session_id'), ['session_id'], unique=False)

    op.create_table('emotional_checklist_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['emotional_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotional_checklist_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emotional_checklist_selections_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotional_checklist_selections_module'), ['module'], unique=False)

    op.create_table('emotional_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.Integer(), nullable=False),
    sa.Column('is_scored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['emotional_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotional_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emotional_responses_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotional_responses_module'), ['module'], unique=False)

    op.create_table('emotional_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('response_scale', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('severity_band', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('is_clinically_validated', sa.Boolean(), nullable=False),
    sa.Column('crisis_alert', sa.Boolean(), nullable=False),
    sa.Column('professional_help_recommended', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['emotional_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotional_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emotional_scores_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotional_scores_module'), ['module'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emotional_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotional_scores_module'))
        batch_op.drop_index(batch_op.f('ix_emotional_scores_assessment_id'))

    op.drop_table('emotional_scores')
    with op.batch_alter_table('emotional_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotional_responses_module'))
        batch_op.drop_index(batch_op.f('ix_emotional_responses_assessment_id'))

    op.drop_table('emotional_responses')
    with op.batch_alter_table('emotional_checklist_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotional_checklist_selections_module'))
        batch_op.drop_index(batch_op.f('ix_emotional_checklist_selections_assessment_id'))

    op.drop_table('emotional_checklist_selections')
    with op.batch_alter_table('emotional_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotional_assessments_session_id'))

    op.drop_table('emotional_assessments')
    with op.batch_alter_table('crisis_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crisis_resources_country_code'))
        batch_op.drop_index(batch_op.f('ix_crisis_resources_active'))

    op.drop_table('crisis_resources')
    # ### end Alembic commands ###
