"""add response_time_ms to emotional_responses

Revision ID: c53216f78b49
Revises: 943753881737
Create Date: 2026-07-01 20:14:56.243526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53216f78b49'
down_revision: Union[str, Sequence[str], None] = '943753881737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emotional_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_time_ms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emotional_responses', schema=None) as batch_op:
        batch_op.drop_column('response_time_ms')

    # ### end Alembic commands ###
