"""initial schema

Revision ID: fab70df98a04
Revises: 
Create Date: 2026-07-01 00:27:25.720648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fab70df98a04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('norm_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('scope_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('raw_to_percentile_mapping', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('norm_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_norm_tables_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_norm_tables_scope_key'), ['scope_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_norm_tables_version'), ['version'], unique=False)

    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('test_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('email_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('email_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_deliveries_email_hash'), ['email_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_deliveries_session_id'), ['session_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('archetype_label', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_token', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('pdf_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_pdf_token'), ['pdf_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_session_id'), ['session_id'], unique=False)

    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'item_id', name='uq_response_session_item')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_session_id'), ['session_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('scope_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('scope_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'scope_type', 'scope_key', name='uq_score_scope')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_scope_key'), ['scope_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_session_id'))
        batch_op.drop_index(batch_op.f('ix_scores_scope_type'))
        batch_op.drop_index(batch_op.f('ix_scores_scope_key'))

    op.drop_table('scores')
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_session_id'))

    op.drop_table('responses')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_session_id'))
        batch_op.drop_index(batch_op.f('ix_reports_pdf_token'))

    op.drop_table('reports')
    with op.batch_alter_table('email_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_deliveries_session_id'))
        batch_op.drop_index(batch_op.f('ix_email_deliveries_email_hash'))

    op.drop_table('email_deliveries')
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_test_sessions_status'))

    op.drop_table('test_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('norm_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_norm_tables_version'))
        batch_op.drop_index(batch_op.f('ix_norm_tables_scope_key'))
        batch_op.drop_index(batch_op.f('ix_norm_tables_active'))

    op.drop_table('norm_tables')
    # ### end Alembic commands ###
